### ISSUE TITLE
Import concepts does not support more overlap in CUI between cdbs

### ISSUE THREAD

**Issue by zack-kimble** [CogStack/MedCATtrainer#55]
Attempting to import concepts from a CDB that has some CUI already imported  from another CDB will fail because of `sqlite3.IntegrityError: UNIQUE constraint failed: api_concept.cui`.

This is because the Concept class requires `cui` to be unique, but `_import_concepts` only checks for existing cuis for the same cdb, not all cdbs:
```
    existing_cuis = set(Concept.objects.filter(cdb=id).values_list('cui', flat=True))

    for cui in cdb.cui2names.keys():
        if cui not in existing_cuis:
 ```
 
 As it is, this prevents the use of multiple CDB's from the same terminological system. To support multiple CDB's, I think either CDB's will need to be able to share concepts in the trainer or the unique ID in concepts will need to be based on cui and cdb_id. I realize both of these have their own drawbacks.

**Comment by tomolopolis** [comment]
This is by design.  Ideally, the CDB you'll import and run _import_concepts on will be the 'main' CDB, this will contain all terms for a given terminological system. This 'main' CDB could then be filtered down / adjusted for a given project (outside of the trainer), or you could re-use this CDB and use the json file filter or csv filter tex field directly in each project.

The [ConceptPicker](https://github.com/CogStack/MedCATtrainer/blob/master/webapp/frontend/src/components/common/ConceptPicker.vue#L97) component, uses the set of CDB Ids from the project.cdb_search_filter param and the current CDB used for the NER+L (this is because an annotator may create new concepts that would then be searchable by themselves or further annotators in that project).

**Comment by tomolopolis** [comment]
this has been changed, not with a composite key on cdb_id & cui, but we simply overwrite the Concept.cdb_model with the latest imported or added ConceptDb model id. So there's still only one Concept per terminological systems (i.e. cui's are unique in trainer), but you don't have to remember to clear out an 'old' CDBs set of concepts before importing from a 'new' cdb.

Hope that helps!

https://github.com/CogStack/MedCATtrainer/commit/7ef47d4475b922c39105219c4098e63882b8f4bd
