### ISSUE TITLE
Problems with concept picker

### ISSUE THREAD

**Issue by OJay92** [CogStack/MedCATtrainer#57]
- Set up a new annotation project with a CDB file (that was saved in MedCAT trainer earlier) and started to annotate letters. 

- However trying to add new terms, the concept picker does not seem to recognise existing alternatives (concept lookup) and were also getting an error when adding new concepts manually

- Tried to follow the steps from the readme ==> import concepts in the concept DB entry via the admin app but this also does not solve the issue ?

(- When using an old/ the initial CDB file we are suddenly able again to add concepts)

Does this sound familiar or any thought on how to fix this?

**Comment by tomolopolis** [comment]
are you using the `image: cogstacksystems/medcat-trainer:v2.2.1` ?

After you import the concepts from the CDB do you see those concepts available in the Concepts table in the Django admin, e.g. (at the url of your deployed trainer instance <host>:<port>/admin/api/concept/  you should see those concepts you've imported from the CDB)

Each project's concept picker is configured to search across this django Concepts table via 2 CDBs. The CDB for the currently configured project, (`Concept DB` and the CDB configured under `Cdb search filter`. This is because one deployment may have multiple projects with annotators adding custom concepts, which should not appear across other projects. 

The CDB configured under `CDB Search filter` should be a 'plain' CDB that is not used for training / configured directly to a project and imported once.

**Comment by sandertan** [comment]
Hi @tomolopolis , yes we're using commit e8496be814c65b9fd21ce9b08add27e021d76f71 which is in v2.2.1 release.

> After you import the concepts from the CDB do you see those concepts available in the Concepts table in the Django admin, e.g. (at the url of your deployed trainer instance :/admin/api/concept/ you should see those concepts you've imported from the CDB)

Yes we see those concepts, but after uploading an updated CDB (containing modified CUI names & some CUIs removed) it's difficult to find if the modified CUIs are imported correctly because there are too many pages to find the CUI manually.

> CDB Search filter

In a new medcattrainer project, when we select None or the updated CDB in `CDB Search filter`, the API (in both cases `?search=diabetes&cdb__in=2` never returns any search suggestions. Selecting the previous project's CDB `?search=diabetes&cdb__in=1` or Both `?search=diabetes&cdb__in=1,2` does return Search results (I assume only from the first CDB), but for this project we'd like to only use the updated CDB.

**Comment by tomolopolis** [comment]
hi @sandertan - sorry for the delay in response, ah I see what you mean. I think you need to remove all the concepts from the old CDB using the option Delete concepts from CDB. 
![screenshot](https://user-images.githubusercontent.com/6503604/149976786-1d4b1ba2-f3d3-49be-bf5e-185b859206ca.png) 
then import again those concepts from that new CDB. we have a unique constraint on the cui field of the concept, we can consider moving this to composite primary key of cui and cdb...

**Comment by sandertan** [comment]
@tomolopolis ah right! Indeed that solves it. In the current situation we are only using 1 CDB per MCT instance, so keeping the concepts DB in sync by removing & adding concepts in the admin panel is workable for us.

**Comment by tomolopolis** [comment]
bit slow on this one, but finally got around to Concept models now overwrite Concept models that have the same CUI if they are being imported from some other CDB.

https://github.com/CogStack/MedCATtrainer/commit/7ef47d4475b922c39105219c4098e63882b8f4bd

**Comment by tomolopolis** [comment]
available now in :latest, :v2.2.4
